from ashenmoor.world import Room
from . import objects as O
from . import mobs    as M

ROOMS: dict[int, Room] = {
    5: Room({
        "number": 5,
        "name": "Mrs.Allisons class",
        "description": "you are in a room, a plethora of fancy historical dupes surround you on the walls",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "south", "roomId": 1},
        ],
        "objects": [
            #O.spawn("water bottle"),
            #O.spawn("pitch fork")
        ],
        "mobs": [M.spawn("malcom")],
    }),
    6: Room({
        "number": 6,
        "name": "Miss Allisons",
        "description": "a room, filled with modern decor, accompanied by historical papers and a wooden map that adorns half of the west wall",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "south", "roomId": 2},
        ],
        "objects": [],
        "mobs": [],
    }),
    7: Room({
        "number": 7,
        "name": "Mrs. Millers",
        "description": "a lightly decorated room with geometrically shaped desks and animal tanks.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "north", "roomId": 1},
        ],
        "objects": [],
        #"mobs": ["The Beast of Geometry and Algebra"],
    }),
    8: Room({
        "number": 8,
        "name": "Mr. Westmarks",
        "description": "a small office litters with books and trinkets, one cluttered desk sits with three office chairs",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "south", "roomId": 4},
        ],
        "objects": [],
        "mobs": [],
    }),
    9: Room({
        "number": 9,
        "name": "Mr. Millers class",
        "description": "a bland room with few decorations, two couches sit in the back.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "south", "roomId": 3},
        ],
        "objects": [],
        "mobs": [],
    }),
    10: Room({
        "number": 10,
        "name": "Mr. Stubblefield",
        "description": "a bland room with some decorations, a cluttered desk sits in the corner along with two cluttered counters in the back",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 9},
        ],
        "objects": [],
        "mobs": [],
    }),
    11: Room({
        "number": 11,
        "name": "Mrs. Kralicek",
        "description": "a well decorated room filled with a sweet smell, many literature related posters sit on the walls",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "north", "roomId": 3},
        ],
        "objects": [],
        "mobs": [],
    }),
    1: Room({
        "number": 1,
        "name": "hallway seg 1",
        "description": "lockers line the walls on the south, accompanied by a door.\nbackpacks hangs nest to another door on the east",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 2},
            {"direction": "south", "roomId": 9},
            {"direction": "north", "roomId": 5},
            {"direction": "west", "roomId": 99004},
        ],
        "objects": [],
        "mobs": [],
    }),
    2: Room({
        "number": 2,
        "name": "hallway seg 2",
        "description": "lockers line the walls on the south, accompanied by a door.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 3},
            {"direction": "south", "roomId": 10},
            {"direction": "west", "roomId": 1},
            {"direction": "north", "roomId": 6},
        ],
        "objects": [],
        "mobs": [],
    }),
    3: Room({
        "number": 3,
        "name": "hallway seg 3",
        "description": "lockers line the walls on the south, accompanied by a door.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 4},
            {"direction": "south", "roomId": 11},
            {"direction": "west", "roomId": 2},
            {"direction": "north", "roomId": 7},
        ],
        "objects": [],
        "mobs": [],
    }),
    4: Room({
        "number": 4,
        "name": "hallway seg 4",
        "description": "lockers line the walls on the south, accompanied by a door.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "north", "roomId": 8},
            {"direction": "west", "roomId": 3},
            {"direction": "east", "roomId": 16},
            {"direction": "south", "roomId": 11},
        ],
        "objects": [],
        "mobs": [],
    }),
    15: Room({
        "number": 15,
        "name": "Mr. C's office",
        "description": "this room is filled with a subtle intensity of past punishment, many hunting related decor are hung here.",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "north", "roomId": 16},
            {"direction": "down", "roomId": 5},
        ],
        "objects": [],
        "mobs": [],
    }),
    
    12: Room({
        "number": 12,
        "name": "bathroom 1",
        "description": "you are in a clean but &Gacrid&N smelling room, few items can be found here",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 17},
        ],
        "objects": [],
        "mobs": [],
    }),
    13: Room({
        "number": 13,
        "name": "bathroom 2",
        "description": "you are in a clean but &Gacrid&N smelling room, few items can be found here",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 18},
        ],
        "objects": [],
        "mobs": [],
    }),
    14: Room({
        "number": 14,
        "name": "bathroom 3",
        "description": "you are in a clean but &Gacrid&N smelling room, few items can be found here",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "east", "roomId": 19},
        ],
        "objects": [],
        "mobs": [],
    }),
    16: Room({
        "number": 16,
        "name": "hallway seg 5",
        "description": "you have found a crossroads of hallway. where will your adventure commence?",
        "indoors": True,
        "terrain": "ground",
        "exits": [
            {"direction": "north", "roomId": 15},
            {"direction": "west", "roomId": 4},
            {"direction": "south", "roomId": 17},
        ],
        "objects": [],
        "mobs": [M.spawn("Enemy")],
    }),

}
